name: 'Setup Node Environment'
description: 'Setup Node.js and pnpm, and install dependencies'

inputs:
  registry-url:
    description: 'Optional npm registry URL for publishing (e.g., https://registry.npmjs.org)'
    required: false
    default: ''
  install-timeout:
    description: 'Timeout in minutes for pnpm install (default: 5)'
    required: false
    default: '5'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '22.12.0'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
