name: 'Setup Node Environment'
description: 'Setup Node.js and pnpm, and install dependencies'

inputs:
  registry-url:
    description: 'npm registry URL (optional)'
    required: false
    default: ''
  install-timeout:
    description: 'Timeout in minutes for pnpm install'
    required: false
    default: '2'
  node-version:
    description: 'Node.js version'
    required: false
    default: '22.12.0'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        registry-url: ${{ inputs.registry-url != '' && inputs.registry-url || null }}

    - name: Install dependencies
      run: pnpm install --frozen-lockfile --reporter=append-only
      shell: bash
      env:
        PNPM_INSTALL_TIMEOUT: ${{ inputs.install-timeout }}
